### ISSUE TITLE
Coordinate class?

### ISSUE THREAD

**Issue by bterwijn** [dirkspan/Gridmeisters#1]
Misschien is het handig om een Coordinate class te maken met self.x en self.y?

Of misschien een coordinaat schrijven als lijst: [1,2] of tuple: (1,2).

**Comment by anouarbousraou** [comment]
Waar is dit voor nodig? bedoelt u dat wij de locaties van de batterijen en huizen hiermee moeten definiëren of is dit handig om de coordinaten tussen batterijen en huizen aan te roepen?

**Comment by bterwijn** [comment]
> Waar is dit voor nodig? bedoelt u dat wij de locaties van de batterijen en huizen hiermee moeten definiëren of is dit handig om de coordinaten tussen batterijen en huizen aan te roepen?

**Comment by bterwijn** [comment]
Niet perse nodig, maar ik denk dat dat je code korter en makkelijker te lezen maakt. Alleen maar een suggestie.
Dan krijgt bv house een self.coordinate i.p.v. self.x en self.y. Zo'n x en y samen zijn 1 ding, een coordinaat, dan is het naar mijn idee logischer om er 1 class voor te maken.

**Comment by anouarbousraou** [comment]
Klopt u heeft gelijk ik zal het aanpassen, bedankt voor de feedback bas :)
